"""Whether a verified machine may receive customer work.

Audit work and customer work are not admitted the same way. Audit work is
generated by the validator, is worth one clause count, and exists to prove a
machine is alive. Customer work carries someone else's payload and returns a
result they rely on.

Today the dispatcher sends customer work to any miner that answers
``{"customer_sat": true}`` on ``/v1/capabilities``. That is a claim made by
code the machine's operator controls.

This module adds the decision that is missing, and nothing else. It is not a
second policy type: :class:`cathedral.common.Policy` already carries
``allowed_measurements`` and the registry binding, and the verifier already
returns the measurement, TCB and advisory state on
:class:`cathedral.common.Attested`. TCB floors, advisory rejection and
``tdx_strict`` remain the verifier's job — re-checking them here would be a
second implementation of the same rule.

What this adds is the refusal, including two refusals the first version of
this module got wrong:

- A hand-built or duck-typed object is not a verdict. The inputs are type
  checked, because :class:`Attested` is a plain frozen dataclass with no
  provenance of its own.

**What this function cannot do, and must not be trusted to do.** The type
check is not provenance. :class:`Attested` defaults ``chain_verified=True``
and ``verification_status="VERIFIED"``, so a caller holding a real
unverified verdict can recompute the fields, and the TDX path never sets
them at all. A process that can construct an :class:`Attested` can satisfy
this gate. It is a refusal for an honest caller and a second pair of eyes on
a mistaken one; it is not a defence against a caller that wants to lie. The
real control is to keep this decision in the process that runs the verifier,
or to make the verdict carry provenance that cannot be recomputed.
- ``chain_verified`` and ``verification_status`` are part of the decision.
  The SNP verifier can return ``STRUCTURE_OK_CHAIN_UNVERIFIED``, and its own
  docstring states that verdict *"must never be used for admission."*

Every path fails closed.
"""

from __future__ import annotations

from cathedral.common import Attested, Policy, Tier
from cathedral.verify.snp import VERIFIED

__all__ = [
    "CONFIDENTIAL_CPU_TIERS",
    "ADMISSIBLE_VERIFICATION_STATUSES",
    "admits_customer_work",
]

#: Tiers whose answer to "is this confidential?" is yes at the hardware level.
CONFIDENTIAL_CPU_TIERS = frozenset({Tier.CC_CPU_TDX, Tier.CC_CPU_SNP})

#: Verdicts this gate accepts. ``STRUCTURE_OK_CHAIN_UNVERIFIED`` is a
#: diagnostic verdict; the verifier documents it as unusable for admission.
ADMISSIBLE_VERIFICATION_STATUSES = frozenset({VERIFIED})


def admits_customer_work(
    policy: Policy,
    attested: Attested | None,
    *,
    required_tier: Tier | None = None,
) -> bool:
    """Whether customer work may be sent to a machine.

    ``policy`` is the caller's own allowlist. ``attested`` must come from
    verifying fresh evidence, never from a worker's capability response: a
    measurement that arrived over the same wire as the claim is a claim.

    ``required_tier`` defaults to None, which admits either confidential CPU
    family. A caller that needs one family must pass it; the default is
    deliberately permissive between families, never between verified and
    unverified.

    Returns True only when the tier is confidential, the policy names at least
    one measurement, and the measurement is listed, and the verdict does not
    carry a known-unverified marker.

    It does **not** establish that the verdict was produced by a verifier.
    :class:`Attested` defaults ``chain_verified=True`` and
    ``verification_status="VERIFIED"``, and ``cathedral/verify/mock.py`` builds
    verdicts without setting either, so a defaulted or hand-built verdict with
    an allowlisted measurement is admitted. Use this as a refusal for an honest
    caller, never as a security boundary.
    """

    if not isinstance(policy, Policy):
        return False
    # Exact type, not isinstance. Attested is a plain dataclass whose fields
    # are read as attributes, so a subclass can shadow ``tier`` or
    # ``measurement`` with a property and present an allowlisted value while
    # the real payload is something else. isinstance cannot see that.
    if type(attested) is not Attested:
        return False
    # `is True` and an exact str check, not truthiness or a bare set lookup: a
    # truthy string such as "false" passes a bare test, and an unhashable status
    # raises from membership instead of refusing.
    if attested.chain_verified is not True:
        return False
    if not isinstance(attested.verification_status, str):
        return False
    if attested.verification_status not in ADMISSIBLE_VERIFICATION_STATUSES:
        return False
    # The compatibility TDX path skips the debug and collateral gates and
    # returns a verdict carrying dataclass defaults, so a debug-enabled platform
    # would otherwise be admitted. Refuse rather than infer.
    if attested.debug_enabled is not False:
        return False
    if attested.collateral_current is False:
        return False
    if not policy.allowed_measurements:
        # An empty allowlist denies everything. It must never mean "any".
        return False
    # Tier is a str enum, so a bare string compares equal to a member and would
    # pass a membership test. Demand the enum itself.
    if not isinstance(attested.tier, Tier):
        return False
    if required_tier is not None:
        # A caller that names a tier must name a confidential one. Without this
        # a typo or a deliberate CC_GPU pin would admit a non-confidential
        # verdict through the branch below.
        if not isinstance(required_tier, Tier):
            return False
        if required_tier not in CONFIDENTIAL_CPU_TIERS:
            return False
        if attested.tier is not required_tier:
            return False
    elif attested.tier not in CONFIDENTIAL_CPU_TIERS:
        return False
    measurement = attested.measurement
    if not measurement or not isinstance(measurement, str):
        # A non-string would otherwise reach set membership, where an
        # unhashable value raises instead of refusing.
        return False
    return measurement in policy.allowed_measurements
